on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - run: |
          sudo npm install -g yarn lerna
          lerna bootstrap
          lerna link
          lerna run full
          lerna run lint