on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - run: |
          sudo npm install -g yarn lerna
          lerna bootstrap
          lerna run build
          lerna run tc
          lerna run lint
      # - uses: JamesIves/github-pages-deploy-action@4.1.4
      #   with:
      #     branch: gh-pages
      #     folder: examples/hatra/dist